[phases.setup]
nixPkgs = ["unixODBC", "freetds"]

[phases.install]
cmds = ["curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg", "install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/", "sh -c 'echo \"deb [arch=amd64] https://packages.microsoft.com/debian/11/prod bullseye main\" > /etc/apt/sources.list.d/mssql-release.list'", "apt-get update", "ACCEPT_EULA=Y apt-get install -y msodbcsql18"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
